version: '3.7'

services:
  openai-integration:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: openai-integration
    expose:
      - '8002'
    ports:
      - '8002:8002'
    command: npm run dev